Repository Inist-CNRS/web-services, pull requests merged in 2024-11, with the labels that each got.

#195 [data-topcitation) : choose the number of citations to return
  services/data-topcitation/v1/retrieve-json.ini
  services/data-topcitation/v1/topcitation.ini
  services/data-topcitation/v1/topcitation.py
Labels: enhancement

#199 (data-topcitation) change output
  package-lock.json
  services/data-topcitation/README.md
  services/data-topcitation/examples.http
  services/data-topcitation/package.json
  services/data-topcitation/swagger.json
  services/data-topcitation/tests.hurl
  services/data-topcitation/v1/topcitation.py
Labels: enhancement, waiting "make publish"

#196 (affiliations-tools/ror) change geonames path
  package-lock.json
  services/affiliations-tools/README.md
  services/affiliations-tools/examples.http
  services/affiliations-tools/package.json
  services/affiliations-tools/swagger.json
  services/affiliations-tools/tests.hurl
  services/affiliations-tools/v1/ror/get-id.ini
  services/affiliations-tools/v1/ror/get-id.py
Labels: enhancement, waiting "make publish"

#197 [text-clustering] change algorithm
  package-lock.json
  services/text-clustering/Dockerfile
  services/text-clustering/README.md
  services/text-clustering/package.json
  services/text-clustering/swagger.json
  services/text-clustering/v1/clustering.ini
  services/text-clustering/v1/clustering.py
  services/text-clustering/v1/noise-process.py
  services/text-clustering/v1/noise.ini
  services/text-clustering/v1/noise.py
Labels: enhancement, waiting "make publish"

#203 Remove package-lock.json
  .gitignore
  .nvmrc
  package-lock.json
  package.json
Labels: enhancement

#200 perf(biblio-ref): add premium crossref token
  .github/workflows/test-and-publish-on-tag.yml
  .github/workflows/test-on-branch.yml
  bin/create-env.sh
  services/biblio-ref/.env.example
  services/biblio-ref/README.md
  services/biblio-ref/config.json
  services/biblio-ref/package.json
  services/biblio-ref/swagger.json
  services/biblio-ref/v1/bibref/bibref_functions.py
  services/biblio-ref/v1/validate-pdf.py
  services/biblio-ref/v1/validate-url.ini
  services/biblio-ref/v1/validate-url.py
  services/biblio-ref/v1/validate.ini
  services/biblio-ref/v1/validate.py
Labels: enhancement, waiting "make publish"

#205 [biblio-tools] fix openalex/v2/works/expand abstract
  .vscode/settings.json
  services/biblio-tools/README.md
  services/biblio-tools/package.json
  services/biblio-tools/swagger.json
  services/biblio-tools/v2/openalex/works/expand.ini
Labels: bug

#207 [biblio-tools] Some abstracts were strangley rebuilt
  services/biblio-tools/README.md
  services/biblio-tools/package.json
  services/biblio-tools/swagger.json
  services/biblio-tools/v2/openalex/works/expand.ini
Labels: bug

#204 feat(data-thesesul): breaking change : changed output
  services/data-thesesul/.dockerignore
  services/data-thesesul/README.md
  services/data-thesesul/config.json
  services/data-thesesul/package.json
  services/data-thesesul/push-on-hal.sh
  services/data-thesesul/swagger.json
  services/data-thesesul/tests.hurl
  services/data-thesesul/v1/retrieve-tests.ini
  services/data-thesesul/v1/retrieve-tests.py
  services/data-thesesul/v1/sudoc.py
  services/data-thesesul/v1/thesesul/__init__.py
  services/data-thesesul/v1/thesesul/thesesul_functions.py
Labels: waiting "make publish"

#209 [data-workflow] avoid having json in csv
  services/data-workflow/README.md
  services/data-workflow/package.json
  services/data-workflow/swagger.json
  services/data-workflow/v1/retrieve-csv.ini
Labels: waiting "make publish"

#210 fix(diseases-ner): fix how to get entities
  services/diseases-ner/README.md
  services/diseases-ner/package.json
  services/diseases-ner/swagger.json
  services/diseases-ner/v1/diseases/tagger.py
Labels: bug, waiting "make publish"

#211 fix(chem-ner): fix how to get entities
  services/chem-ner/README.md
  services/chem-ner/package.json
  services/chem-ner/swagger.json
  services/chem-ner/v1/chem/tagger.py
Labels: bug, waiting "make publish"
