Repository Inist-CNRS/web-services, pull requests merged in 2024-09, with the labels that each got.

#169 Add package-lock.json
  .gitignore
  package-lock.json
Labels: bug

#140 [terms-extraction] update extract quantity version
  services/terms-extraction/Dockerfile
  services/terms-extraction/README.md
  services/terms-extraction/package.json
  services/terms-extraction/swagger.json
  services/terms-extraction/tests.hurl
  services/terms-extraction/v1/quantity/extract.ini
  services/terms-extraction/v1/quantity/extract.py
  services/terms-extraction/v1_quantity_extract.md
Labels: enhancement, waiting "make publish"

#167 feat(biblio-ref): new output for validate-pdf
  services/biblio-ref/README.md
  services/biblio-ref/package.json
  services/biblio-ref/swagger.json
  services/biblio-ref/v1/validate-pdf.ini
  services/biblio-ref/v1/validate-pdf.py
  services/biblio-ref/v1/validate-url.py
Labels: bug, enhancement

#164 Services/address kit/update affiliationcountry
  services/address-kit/README.md
  services/address-kit/config.json
  services/address-kit/examples.http
  services/address-kit/package.json
  services/address-kit/swagger.json
  services/address-kit/tests.hurl
  services/address-kit/v1/affiliationcountry/affilcountry.ini
  services/address-kit/v1/affiliationcountry/detect_country.py
Labels: bug, enhancement, waiting "make publish"

#173 [data-computer]: Increase delays
  services/data-computer/tests.hurl
Labels: bug

#174 [data-termsuite]: Increase delays x1.5
  services/data-termsuite/tests.hurl
Labels: bug

#177 [data-computer]: Use ezs packages from base image
  services/data-computer/Dockerfile
  services/data-computer/README.md
  services/data-computer/package.json
  services/data-computer/swagger.json
Labels: enhancement

#172 Services/terms tools/initial add terms tools
  .gitattributes
  package-lock.json
  package.json
  services/terms-tools/.dockerignore
  services/terms-tools/Dockerfile
  services/terms-tools/README.md
  services/terms-tools/config.json
  services/terms-tools/examples.http
  services/terms-tools/package.json
  services/terms-tools/swagger.json
  services/terms-tools/tests.hurl
  services/terms-tools/v1/en/dico_annot/postag.ini
  services/terms-tools/v1/en/dico_pos/postag.ini
  services/terms-tools/v1/en/full_morph/postag.ini
  services/terms-tools/v1/fr/dico_annot/postag.ini
  services/terms-tools/v1/fr/dico_pos/postag.ini
  services/terms-tools/v1/fr/full_morph/postag.ini
Labels: enhancement
