Repository Inist-CNRS/web-services, pull requests merged in 2024-10, with the labels that each got.

#180 (data-topcitation) Ajout du WS asynchrone sur les références phares
  README.md
  package.json
  services/data-topcitation/.dockerignore
  services/data-topcitation/Dockerfile
  services/data-topcitation/README.md
  services/data-topcitation/config.json
  services/data-topcitation/examples.http
  services/data-topcitation/examples/list-doi.tar.gz
  services/data-topcitation/package.json
  services/data-topcitation/swagger.json
  services/data-topcitation/swagger.md
  services/data-topcitation/tests.hurl
  services/data-topcitation/v1/buffer.cfg
  services/data-topcitation/v1/charger.cfg
  services/data-topcitation/v1/logger.cfg
  services/data-topcitation/v1/recipient.cfg
  services/data-topcitation/v1/recorder.cfg
  services/data-topcitation/v1/retrieve-csv.ini
  services/data-topcitation/v1/retrieve-json.ini
  services/data-topcitation/v1/retrieve.ini
  services/data-topcitation/v1/topcitation.ini
  services/data-topcitation/v1/topcitation.py
Labels: enhancement, waiting "make publish"

#179 fix(data-computer): update hyperparameters
  services/data-computer/README.md
  services/data-computer/package.json
  services/data-computer/swagger.json
  services/data-computer/v1/lda.py
Labels: enhancement, waiting "make publish"

#188 [data-topcitation] bug doi null
  package-lock.json
  services/data-topcitation/README.md
  services/data-topcitation/package.json
  services/data-topcitation/swagger.json
  services/data-topcitation/tests.hurl
  services/data-topcitation/v1/topcitation.py
Labels: bug, waiting "make publish"

#138 [data computer] add corpus similarity ws
  package-lock.json
  services/data-computer/README.md
  services/data-computer/example-similarity-json.tar.gz
  services/data-computer/examples.http
  services/data-computer/package.json
  services/data-computer/swagger.json
  services/data-computer/tests.hurl
  services/data-computer/v1/corpus-similarity.ini
  services/data-computer/v1/corpus-similarity.py
Labels: enhancement

#187 [data-thesesul] create service
  README.md
  package-lock.json
  package.json
  services/data-thesesul/.dockerignore
  services/data-thesesul/Dockerfile
  services/data-thesesul/README.md
  services/data-thesesul/config.json
  services/data-thesesul/example.tar.gz
  services/data-thesesul/examples.http
  services/data-thesesul/package.json
  services/data-thesesul/swagger.json
  services/data-thesesul/tests.hurl
  services/data-thesesul/v1/buffer.cfg
  services/data-thesesul/v1/charger.cfg
  services/data-thesesul/v1/logger.cfg
  services/data-thesesul/v1/recipient.cfg
  services/data-thesesul/v1/recorder.cfg
  services/data-thesesul/v1/retrieve-tests.ini
  services/data-thesesul/v1/retrieve-tests.py
  services/data-thesesul/v1/retrieve.ini
  services/data-thesesul/v1/sudoc.ini
  services/data-thesesul/v1/sudoc.py
  services/data-thesesul/v1/xsl-files.tar.gz.dvc
Labels: enhancement, waiting "make publish"

#193 [loterre-resolvers]: Move databases into /app/public
  package-lock.json
  services/loterre-resolvers/README.md
  services/loterre-resolvers/docker-entrypoint.sh
  services/loterre-resolvers/package.json
  services/loterre-resolvers/swagger.json
  services/loterre-resolvers/v1/combine.cfg
Labels: bug
