Repository Inist-CNRS/web-services, pull requests merged in 2024-06, with the labels that each got.

#88 Services/sciencemetrix classification/make service
  README.md
  package.json
  services/sciencemetrix-classification/.dockerignore
  services/sciencemetrix-classification/Dockerfile
  services/sciencemetrix-classification/README.md
  services/sciencemetrix-classification/config.json
  services/sciencemetrix-classification/examples.http
  services/sciencemetrix-classification/package.json
  services/sciencemetrix-classification/swagger.json
  services/sciencemetrix-classification/tests.hurl
  services/sciencemetrix-classification/v1/classif.ini
  services/sciencemetrix-classification/v1/classif.py
  services/sciencemetrix-classification/v1/id2label.pickle
  services/sciencemetrix-classification/v1/model.bin.dvc
Labels: enhancement

#92 biblio-tools: migrate from gitbucket
  .github/workflows/docker-build-on-push.yml
  .github/workflows/docker-build-on-tag.yml
  CONTRIBUTING.md
  README.md
  bin/create-env.sh
  package.json
  services/biblio-tools/.dockerignore
  services/biblio-tools/Dockerfile
  services/biblio-tools/README.md
  services/biblio-tools/config.json
  services/biblio-tools/examples.http
  services/biblio-tools/package.json
  services/biblio-tools/swagger.json
  services/biblio-tools/tests.hurl
  services/biblio-tools/v1/conditor/works/expand.ini
  services/biblio-tools/v1/conditor/works/expandByHalid.ini
  services/biblio-tools/v1/crossref/prefixes/expand.ini
  services/biblio-tools/v1/crossref/works/expand.ini
  services/biblio-tools/v1/datacite/works/expand.ini
  services/biblio-tools/v1/hal/works/expand.ini
  services/biblio-tools/v1/inspirehep/works/expand.ini
  services/biblio-tools/v1/istex/works/expand.ini
  services/biblio-tools/v1/openalex/works/expand.ini
  services/biblio-tools/v1/rdg/works/expand.ini
  services/biblio-tools/v1/unpaywall/corhal.ini
  services/biblio-tools/v1/unpaywall/expand.ini
  services/biblio-tools/v1/unpaywall/is_oa.ini
  services/biblio-tools/v1/unpaywall/works/expand.ini
  services/biblio-tools/v1/wos/fetch.ini
  services/biblio-tools/v1/wos/works/expand.ini
  services/biblio-tools/v1/wos/works/expandByUT.ini
  services/biblio-tools/v2/conditor/works/expand.ini
  services/biblio-tools/v2/conditor/works/expandByHalid.ini
  services/biblio-tools/v2/crossref/prefixes/expand.ini
  services/biblio-tools/v2/crossref/works/expand.ini
  services/biblio-tools/v2/datacite/works/expand.ini
  services/biblio-tools/v2/hal/works/expand.ini
  services/biblio-tools/v2/inspirehep/works/expand.ini
  services/biblio-tools/v2/istex/works/expand.ini
  services/biblio-tools/v2/openalex/works/expand.ini
  services/biblio-tools/v2/rdg/works/expand.ini
  services/biblio-tools/v2/unpaywall/corhal.ini
  services/biblio-tools/v2/unpaywall/expand.ini
  services/biblio-tools/v2/unpaywall/is_oa.ini
  services/biblio-tools/v2/unpaywall/works/expand.ini
  services/biblio-tools/v2/wos/fetch.ini
  services/biblio-tools/v2/wos/works/expand.ini
  services/biblio-tools/v2/wos/works/expandByUT.ini
Labels: migration

#90 fix(sciencemetrix-classification): update output
  services/sciencemetrix-classification/README.md
  services/sciencemetrix-classification/examples.http
  services/sciencemetrix-classification/package.json
  services/sciencemetrix-classification/swagger.json
  services/sciencemetrix-classification/tests.hurl
  services/sciencemetrix-classification/v1/all-classif.pickle
  services/sciencemetrix-classification/v1/classif.ini
  services/sciencemetrix-classification/v1/classif.py
Labels: enhancement

#89 Create a new base containing pytorch
  bases/ezs-python-pytorch-server/.dockerignore
  bases/ezs-python-pytorch-server/Dockerfile
  bases/ezs-python-pytorch-server/README.md
  bases/ezs-python-pytorch-server/config.json
  bases/ezs-python-pytorch-server/package.json
  bases/ezs-python-pytorch-server/public/test.ini
  bases/ezs-python-pytorch-server/public/test.py
  package.json
Labels: enhancement

#93 [data-workflow] Migrate from GitBucket
  README.md
  bin/build-and-test.sh
  package.json
  services/data-termsuite/v1/retrieve-json.ini
  services/data-workflow/.dockerignore
  services/data-workflow/22-txt-en.tar.gz
  services/data-workflow/Dockerfile
  services/data-workflow/README.md
  services/data-workflow/config.json
  services/data-workflow/examples.http
  services/data-workflow/package.json
  services/data-workflow/real-tests.hurl
  services/data-workflow/swagger.json
  services/data-workflow/tests.hurl
  services/data-workflow/v1/base-line.ini
  services/data-workflow/v1/buffer.cfg
  services/data-workflow/v1/charger.cfg
  services/data-workflow/v1/conditormetrie.cfg
  services/data-workflow/v1/conditormetrie.ini
  services/data-workflow/v1/logger.cfg
  services/data-workflow/v1/recipient.cfg
  services/data-workflow/v1/recorder.cfg
  services/data-workflow/v1/retrieve-csv.ini
  services/data-workflow/v1/retrieve-json.ini
  services/data-workflow/v1/retrieve.ini
  services/data-workflow/v1/tag-cloud-en.ini
  services/data-workflow/v1/tag-cloud-fr.ini
  services/data-workflow/v1/tag-cloud.cfg
Labels: migration

#94 [address-kit]:migrate from gitbucket
  README.md
  package.json
  services/address-kit/.dockerignore
  services/address-kit/Dockerfile
  services/address-kit/README.md
  services/address-kit/config.json
  services/address-kit/examples.http
  services/address-kit/package.json
  services/address-kit/swagger.json
  services/address-kit/tests.hurl
  services/address-kit/v1/affiliationcountry/affilcountry.ini
  services/address-kit/v1/affiliationcountry/detect_country.py
  services/address-kit/v1/cnrsunit/cnrsunit.ini
  services/address-kit/v1/cnrsunit/dico_codeunite_intituleunite_v071122.pkl
  services/address-kit/v1/cnrsunit/ws_umr.py
Labels: migration

#95 [hal classifier]: fix fr
  services/hal-classifier/README.md
  services/hal-classifier/examples.http
  services/hal-classifier/package.json
  services/hal-classifier/swagger.json
  services/hal-classifier/tests.hurl
  services/hal-classifier/v1/fr/classhalfr.ini
  services/hal-classifier/v1/fr/dist_FAISSkn3_HAL_fr_v1.py
Labels: bug

#80 feat(astro-ner): migrate astro-ner
  README.md
  package.json
  services/astro-ner/.dockerignore
  services/astro-ner/Dockerfile
  services/astro-ner/README.md
  services/astro-ner/config.json
  services/astro-ner/examples.http
  services/astro-ner/package.json
  services/astro-ner/requirements.txt
  services/astro-ner/swagger.json
  services/astro-ner/tests.hurl
  services/astro-ner/v1/find-astro.py
  services/astro-ner/v1/model.dvc
  services/astro-ner/v1/tagger.ini
Labels: migration

#98 [astro-ner]: Deploy 1.0.8
  services/astro-ner/swagger.json
Labels: enhancement

#100 [astro-ner]: use pytorch base image
  bases/ezs-python-pytorch-server/Dockerfile
  bases/ezs-python-pytorch-server/README.md
  bases/ezs-python-pytorch-server/package.json
  services/astro-ner/Dockerfile
  services/astro-ner/README.md
  services/astro-ner/package.json
  services/astro-ner/swagger.json
Labels: enhancement

#91 [diseases-ner] now using the torch base image
  services/diseases-ner/Dockerfile
  services/diseases-ner/README.md
  services/diseases-ner/package.json
  services/diseases-ner/swagger.json
Labels: enhancement

#63 Services/authors tools/migrate
  CONTRIBUTING.md
  README.md
  package.json
  services/authors-tools/.dockerignore
  services/authors-tools/Dockerfile
  services/authors-tools/README.md
  services/authors-tools/config.json
  services/authors-tools/examples.http
  services/authors-tools/package.json
  services/authors-tools/swagger.json
  services/authors-tools/tests.hurl
  services/authors-tools/v1/corporate/abbreviations.json.dvc
  services/authors-tools/v1/corporate/private-public.ini
  services/authors-tools/v1/corporate/private-public.py
  services/authors-tools/v1/first-name/gender.ini
  services/authors-tools/v1/first-name/gender.py
  services/authors-tools/v1/first-name/name_gender.pickle.dvc
  services/authors-tools/v1/orcid-disambiguation/disambiguate.py
  services/authors-tools/v1/orcid-disambiguation/orcidDisambiguation.ini
  services/authors-tools/v1/orcid-disambiguation/orcidDisambiguation.py
Labels: migration

#104 Fix conflicts
  README.md
  package.json
Labels: bug

#99 Migrate domains-classifier
  README.md
  package.json
  services/domains-classifier/.dockerignore
  services/domains-classifier/Dockerfile
  services/domains-classifier/README.md
  services/domains-classifier/classify.py
  services/domains-classifier/code-classement.json
  services/domains-classifier/config.json
  services/domains-classifier/examples.http
  services/domains-classifier/models/__init__.py
  services/domains-classifier/models/models.dvc
  services/domains-classifier/one_prediction.py
  services/domains-classifier/package.json
  services/domains-classifier/swagger.json
  services/domains-classifier/tests.hurl
  services/domains-classifier/tools_prediction.py
  services/domains-classifier/v1/en/classify.ini
Labels: migration

#103 Migrate nlp-tools2
  README.md
  package.json
  services/nlp-tools2/.dockerignore
  services/nlp-tools2/Dockerfile
  services/nlp-tools2/README.md
  services/nlp-tools2/config.json
  services/nlp-tools2/examples.http
  services/nlp-tools2/package.json
  services/nlp-tools2/swagger.json
  services/nlp-tools2/tests.hurl
  services/nlp-tools2/v1/detect-lang.ini
  services/nlp-tools2/v1/detect_lang.py
  services/nlp-tools2/v1/lemma.ini
  services/nlp-tools2/v1/ws_lemmatization.py
Labels: migration

#101 Migrating funder-ner
  README.md
  package.json
  services/funder-ner/.dockerignore
  services/funder-ner/Dockerfile
  services/funder-ner/README.md
  services/funder-ner/config.json
  services/funder-ner/examples.http
  services/funder-ner/package.json
  services/funder-ner/swagger.json
  services/funder-ner/tests.hurl
  services/funder-ner/v1/normalize.py
  services/funder-ner/v1/tagger.ini
  services/funder-ner/v1/tagger.py
  services/funder-ner/v1/v1.dvc
Labels: migration

#102 Migrate ner-tagger
  README.md
  bases/ezs-python-pytorch-server/Dockerfile
  bases/ezs-python-pytorch-server/README.md
  bases/ezs-python-pytorch-server/package.json
  package.json
  services/ner-tagger/.dockerignore
  services/ner-tagger/Dockerfile
  services/ner-tagger/README.md
  services/ner-tagger/config.json
  services/ner-tagger/examples.http
  services/ner-tagger/package.json
  services/ner-tagger/swagger.json
  services/ner-tagger/tests.hurl
  services/ner-tagger/v1/geoTagger/geoTagger.ini
  services/ner-tagger/v1/geoTagger/geoTagger.py
  services/ner-tagger/v1/perseeBaipTagger/tagger.ini
  services/ner-tagger/v1/perseeBaipTagger/tagger.py
  services/ner-tagger/v1/v1.dvc
Labels: migration
