Repository Inist-CNRS/web-services, pull requests merged in 2025-05, with the labels that each got.

#273 test: Increase delays
  services/data-computer/tests.hurl
  services/data-homogenise/tests.hurl
  services/data-rapido/tests.hurl
  services/data-termsuite/tests.hurl
  services/data-thesesul/tests.hurl
  services/data-topcitation/tests.hurl
  services/data-workflow/tests.hurl
  services/data-wrapper/tests.hurl
Labels: test

#274 [data-wrapper] Add txt
  services/data-wrapper/README.md
  services/data-wrapper/package.json
  services/data-wrapper/swagger.json
  services/data-wrapper/tests.hurl
  services/data-wrapper/v1/csv.ini
  services/data-wrapper/v1/txt.ini
Labels: enhancement

#272 (Corpus-similarity) : No more error when no value, add this use case in test
  services/data-computer/README.md
  services/data-computer/example-similarity-json.tar.gz
  services/data-computer/package.json
  services/data-computer/swagger.json
  services/data-computer/tests.hurl
  services/data-computer/v1/corpus-similarity.py
Labels: bug, awaiting publication

#276 Make tests more robust
  services/data-thesesul/tests.hurl
  services/data-topcitation/tests.hurl
  services/data-workflow/tests.hurl
  services/data-wrapper/tests.hurl
Labels: test

#277 [data-table] Add retrieve csv
  services/data-table/package.json
  services/data-table/swagger.json
  services/data-table/tests.hurl
  services/data-table/v1/retrieve-csv.ini
Labels: enhancement

#278 [coara tools] : web service for instance lodex Coara
  README.md
  package.json
  services/coara-tools/.dockerignore
  services/coara-tools/Dockerfile
  services/coara-tools/README.md
  services/coara-tools/config.json
  services/coara-tools/examples.http
  services/coara-tools/package.json
  services/coara-tools/swagger.json
  services/coara-tools/tests.hurl
  services/coara-tools/v1/tools-dict.json
  services/coara-tools/v1/tools.ini
  services/coara-tools/v1/tools.py
Labels: enhancement

#280 [data-computer] Add 2 numbers precision the scores
  services/data-computer/README.md
  services/data-computer/package.json
  services/data-computer/swagger.json
  services/data-computer/tests.hurl
  services/data-computer/v1/corpus-similarity.py
Labels: enhancement, awaiting publication
