Repository Inist-CNRS/web-services, pull requests merged in 2025-02, with the labels that each got.

#246 [data-termsuite] add specificity
  services/data-termsuite/README.md
  services/data-termsuite/package.json
  services/data-termsuite/swagger.json
  services/data-termsuite/swagger.md
  services/data-termsuite/tests.hurl
  services/data-termsuite/v1/extract.sh
  services/data-termsuite/v1/retrieve-json.ini
  services/data-termsuite/v1/tsv2json.mjs
Labels: enhancement

#250 [aiabstract-check]: create ws
  CONTRIBUTING.md
  README.md
  package.json
  services/aiabstract-check/.dockerignore
  services/aiabstract-check/Dockerfile
  services/aiabstract-check/README.md
  services/aiabstract-check/config.json
  services/aiabstract-check/examples.http
  services/aiabstract-check/package.json
  services/aiabstract-check/swagger.json
  services/aiabstract-check/tests.hurl
  services/aiabstract-check/v1/AiAbstract-check.ini
  services/aiabstract-check/v1/AiAbstract-check.py
  services/aiabstract-check/v1/aiAbstract-model.pt.dvc
Labels: awaiting publication

#247 [biblio-ref] : compare doi in lower char + update retracted list
  services/biblio-ref/README.md
  services/biblio-ref/package.json
  services/biblio-ref/swagger.json
  services/biblio-ref/v1/bibref/bibref_functions.py
  services/biblio-ref/v1/csv2pickle.py
  services/biblio-ref/v1/validate.ini
Labels: enhancement, awaiting publication
