Repository Inist-CNRS/web-services, pull requests merged in 2025-01, with the labels that each got.

#214 [authors-tools] Correct output for multiples authors in same request
  services/authors-tools/README.md
  services/authors-tools/package.json
  services/authors-tools/swagger.json
  services/authors-tools/tests.hurl
  services/authors-tools/v1/orcid-disambiguation/orcidDisambiguation.py
Labels: awaiting publication

#231 [terms-extraction] Add v2 of Teeft
  services/terms-extraction/.dockerignore
  services/terms-extraction/README.md
  services/terms-extraction/config.json
  services/terms-extraction/examples.http
  services/terms-extraction/package.json
  services/terms-extraction/swagger.json
  services/terms-extraction/tests.hurl
  services/terms-extraction/v2/teeft/en.ini
  services/terms-extraction/v2/teeft/fr.ini
  services/terms-extraction/v2_teeft_en.md
  services/terms-extraction/v2_teeft_fr.md
Labels: enhancement

#226 [affiliations-tools/ror] Fix error and normalize output
  services/affiliations-tools/README.md
  services/affiliations-tools/package.json
  services/affiliations-tools/swagger.json
  services/affiliations-tools/tests.hurl
  services/affiliations-tools/v1/ror/get-id.py
Labels: awaiting publication

#235 [affiliations tools] Check that tests now work in the CI
  services/affiliations-tools/tests.hurl
  services/affiliations-tools/v1/expand.ini
Labels: test

#236 [data-workflow]: Skip test depending on blocked variable
  services/data-workflow/tests.hurl
  services/data-workflow/v1/base-line.ini
Labels: test

#237 docs(terms-extraction): Fix OpenAPI v2 links
  services/terms-extraction/README.md
  services/terms-extraction/package.json
  services/terms-extraction/swagger.json
  services/terms-extraction/v2/teeft/en.ini
  services/terms-extraction/v2/teeft/fr.ini
Labels: documentation

#238 [text clustering] skip test on GitHub
  services/text-clustering/tests.hurl
  services/text-clustering/v1/clustering.ini
  services/text-clustering/v1/clustering.py
Labels: test

#239 [contributing]: Tip: define HURL_blocked in .bashrc
  CONTRIBUTING.md
Labels: documentation

#240 [data-workflow]: Increase waiting time
  services/data-workflow/tests.hurl
Labels: test

#241 [data-workflow]: Increase waiting time again
  services/data-workflow/tests.hurl
Labels: test

#242 [data-workflow]: Increase delay again and again
  services/data-workflow/tests.hurl
Labels: test

#243 [loterre resolvers] Move databases to /app/data
  services/loterre-resolvers/Dockerfile
  services/loterre-resolvers/README.md
  services/loterre-resolvers/docker-entrypoint.sh
  services/loterre-resolvers/package.json
  services/loterre-resolvers/swagger.json
  services/loterre-resolvers/v1/combine.cfg
Labels: bug

#244 [data-worfklow]: Increase delay (again⁴)
  services/data-workflow/tests.hurl
Labels: test

#227 [data-rapido] Update/bug fix
  services/data-rapido/README.md
  services/data-rapido/package.json
  services/data-rapido/swagger.json
  services/data-rapido/tests.hurl
  services/data-rapido/v1/rapido.py
  services/data-rapido/v1/rapido/alignment.py
  services/data-rapido/v1/rapido/annotations.csv
  services/data-rapido/v1/rapido/annotations.pkl
  services/data-rapido/v1/rapido/export.py
  services/data-rapido/v1/rapido/preprocessing.py
Labels: enhancement, awaiting publication

#245 [loterre-resolvers] /app/data overwritten by Persistent Volume Claim
  services/loterre-resolvers/Dockerfile
  services/loterre-resolvers/README.md
  services/loterre-resolvers/docker-entrypoint.sh
  services/loterre-resolvers/package.json
  services/loterre-resolvers/swagger.json
Labels: bug

#225 [biblio-ref] update service
  services/biblio-ref/README.md
  services/biblio-ref/examples.http
  services/biblio-ref/package.json
  services/biblio-ref/swagger.json
  services/biblio-ref/tests.hurl
  services/biblio-ref/v1/bibref/bibref_functions.py
  services/biblio-ref/v1/references.jsonl
  services/biblio-ref/v1/res.json
  services/biblio-ref/v1/validate-pdf.py
  services/biblio-ref/v1/validate-url.py
  services/biblio-ref/v1/validate.ini
  services/biblio-ref/v1/validate.py
Labels: enhancement, awaiting publication
