Repository Inist-CNRS/web-services, pull requests merged in 2025-06, with the labels that each got.

#292 [data-wrapper] add default value to csv
  services/data-wrapper/README.md
  services/data-wrapper/package.json
  services/data-wrapper/swagger.json
  services/data-wrapper/tests.hurl
  services/data-wrapper/v1/csv.ini
Labels: bug

#283 [text clustering] fix noise detect output
  services/text-clustering/README.md
  services/text-clustering/package.json
  services/text-clustering/swagger.json
  services/text-clustering/v1/noise-process.py
Labels: enhancement, awaiting publication

#296 [coara tools] extract methods from text
  services/coara-tools/Dockerfile
  services/coara-tools/README.md
  services/coara-tools/examples.http
  services/coara-tools/package.json
  services/coara-tools/swagger.json
  services/coara-tools/tests.hurl
  services/coara-tools/v1/fasttext_model.bin.dvc
  services/coara-tools/v1/methods.ini
  services/coara-tools/v1/methods.py
Labels: enhancement, awaiting publication

#297 Save Traefik config files at publishing
  bin/publish.sh
Labels: enhancement
