Repository Inist-CNRS/web-services, pull requests merged in 2025-03, with the labels that each got.

#253 [data-homogenise] add route for ReLM
  services/data-homogenise/README.md
  services/data-homogenise/package.json
  services/data-homogenise/swagger.json
  services/data-homogenise/tests.hurl
  services/data-homogenise/v1/group.ini
  services/data-homogenise/v1/group.py
Labels: enhancement, awaiting publication

#257 [biblio-tools] add expand by hal
  services/biblio-tools/README.md
  services/biblio-tools/package.json
  services/biblio-tools/swagger.json
  services/biblio-tools/tests.hurl
  services/biblio-tools/v2/hal/works/expandByHalId.ini
Labels: enhancement

#258 [terms-tools] Add features to terms-tools
  Unale.txt
  services/terms-tools/.dockerignore
  services/terms-tools/Dockerfile
  services/terms-tools/data.dvc
  services/terms-tools/dictionary.dvc
  services/terms-tools/package.json
  services/terms-tools/swagger.json
  services/terms-tools/tests.hurl
  services/terms-tools/v1/analyze.ini
  services/terms-tools/v1/en/dico_pos/postag.ini
  services/terms-tools/v1/en/terms_matcher/1WB.ini
  services/terms-tools/v1/en/terms_matcher/9SD.ini
  services/terms-tools/v1/en/terms_matcher/P66.ini
  services/terms-tools/v1/fr/terms_matcher/1WB.ini
  services/terms-tools/v1/fr/terms_matcher/9SD.ini
  services/terms-tools/v1/fr/terms_matcher/P66.ini
Labels: enhancement

#260 add an entry point to divide a paragraph into sentences
  services/terms-extraction/README.md
  services/terms-extraction/examples.http
  services/terms-extraction/package.json
  services/terms-extraction/swagger.json
  services/terms-extraction/tests.hurl
  services/terms-extraction/v1/tools/sentences.ini
Labels: awaiting publication
